[workspace]
resolver = "2"

members = [
    "pgpu-render",
    "piet-gpu",
    "piet-gpu-derive",
    "piet-gpu-hal",
    "piet-gpu-types",
    "piet-scene",
    "piet-wgsl",
    "tests",
]

[patch.crates-io]
naga = { path = "../../dl/naga" }
